service: lexus-notify-lambda
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-northeast-1
  environment:
    DYNAMODB_TABLE: lexus_items
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline
custom:
  webpack:
    includeModules: true
  dynamodb:
    stages:
      - dev
    start:
      port: 3030
      inMemory: true
      migrate: true
      seed: true
    seed:
      development:
        sources:
          - table: lexus_items
            sources: [./dynamo/seed.json]
  otherfile:
    environment:
      dev: ${file(./env/dev.yml)}
      prd: ${file(./env/prod.yml)}
resources:
  Resources:
    ArticlesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: lexus_items
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
functions:
  lexusNotify:
    handler: handler.lexusNotify
    events:
      - schedule: cron(5 11,15,19 * * ? *)
    environment:
      LINE_TOKEN: ${self:custom.otherfile.environment.${self:provider.stage}.line.token}